version: '3.8'

services:
  mysql:
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: smartInventory
      MYSQL_ROOT_PASSWORD: Gauravsinghjalal999
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  app:
    build: .
    container_name: smart-inventory-app
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/smartInventory
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Gauravsinghjalal999

volumes:
  mysql-data:

networks:
  backend:
